apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
  namespace: otus-anton
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: order-app
          image: antonkurudinov/otus_hw7_order:1.2
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8003
              name: order-port
          livenessProbe:
            httpGet:
              port: 8003
              path: /order/health
            initialDelaySeconds: 10
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: db-settings
            - secretRef:
                name: db-secret

