apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-app
  namespace: otus-anton
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: erp-app
  template:
    metadata:
      labels:
        app: erp-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: erp-app
          image: antonkurudinov/otus_hw8_erp:1.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8005
              name: erp-port
          livenessProbe:
            httpGet:
              port: 8005
              path: /erp/health
            initialDelaySeconds: 10
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: db-settings
            - secretRef:
                name: db-secret

